# Module with the game parameters
import numpy as np

RNG = np.random.default_rng(42)

ENDOWMENT = 10
CURRENCY = "$"

# Repetitions
NUM_BIG_FIVE_QUESTIONS = 5
MAX_NUM_WAITING_BIG_FIVE_QUESTIONS = 120
NUMBER_OF_ROUNDS = 25
MAX_TIMEOUT_ROUNDS = 5
MAX_FOCUS_LOSS = 3

assert NUM_BIG_FIVE_QUESTIONS >= 1
assert MAX_NUM_WAITING_BIG_FIVE_QUESTIONS > 1

# Waiting times
STANDARD_TIMEOUT = 45
TIMEOUT_WAITING_BIG_FIVE_QUESTIONS = 240
TIMEOUT_WATCH_TUTORIAL = 240
TIMEOUT_WAITING_FOR_OTHER = 2 * STANDARD_TIMEOUT # Max wait at a barrier
TIMEOUT_BETWEEN_BARRIERS = 2 * STANDARD_TIMEOUT # Max time between barriers
WAIT_PAGE_TIME = 3  # Refresh interval at barrier

# Important for Prolific
ESTIMATED_DURATION = 20
HOURLY_PAYMENT = 18
TARGET_PARTICIPANTS = 20

# Rewards
TIME_ESTIMATE_FOR_COMPENSATION = 10
TIME_ESTIMATE_FOR_COMPENSATION_TUTORIAL_VIDEO = 90
PAYMENT_ = HOURLY_PAYMENT / 60 * ESTIMATED_DURATION
PAYMENT = f"{PAYMENT_:.2f}"
REWARD_SCALING_FACTOR = 0.01
MAX_BONUS_REWARD = 5

