# Module with the game parameters
import numpy as np

RNG = np.random.default_rng(42)

ENDOWMENT = 10
CURRENCY = "$"

# Repetitions
NUM_BIG_FIVE_QUESTIONS = 10
MAX_NUM_WAITING_BIG_FIVE_QUESTIONS = 10
NUMBER_OF_ROUNDS = 30
MAX_TIMEOUT_ROUNDS = 2

assert NUM_BIG_FIVE_QUESTIONS >= 1
assert MAX_NUM_WAITING_BIG_FIVE_QUESTIONS > 1

# Waiting times
WAIT_PAGE_TIME = 1.25  # Refresh interval at barrier
STANDARD_TIMEOUT = 45
TIMEOUT_WAITING_FOR_OTHER = 1.25 * STANDARD_TIMEOUT # Max wait at a barrier
TIMEOUT_BETWEEN_BARRIERS = 1.25 * STANDARD_TIMEOUT # Max time between barriers
TIMEOUT_WAITING_BIG_FIVE_QUESTIONS = STANDARD_TIMEOUT
TIMEOUT_PERSONALITY_TEST = TIMEOUT_WAITING_BIG_FIVE_QUESTIONS * (NUM_BIG_FIVE_QUESTIONS + MAX_NUM_WAITING_BIG_FIVE_QUESTIONS)

# Rewards
TIME_ESTIMATE_FOR_COMPENSATION = 5
ESTIMATED_DURATION = 20
HOURLY_PAYMENT = 10
PAYMENT_ = HOURLY_PAYMENT / 60 * ESTIMATED_DURATION
PAYMENT = f"{PAYMENT_:.2f}"
REWARD_SCALING_FACTOR = 0.01
MAX_BONUS_REWARD = 5

